
security:
    role_hierarchy:
      ROLE_ADMIN: [ ROLE_USER ]

    encoders:
        Symfony\Component\Security\Core\User\User: 'bcrypt'

    providers:
        memory:
          memory:
            users: 
                admin: 
                    password: $2y$13$NinsUWF73KPY13oo2kYTSOaU5VG15YwufamhrsmzZEFkOOFUN0Iau
                    roles: [ ROLE_ADMIN ]

        chain_provider:
          chain:
              providers: ['memory']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: chain_provider
            json_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        doc:
            pattern: ^/api/doc
            anonymous: true
            provider: chain_provider

        api:
           pattern:   ^/api
           stateless: true
           provider: chain_provider
           guard:
               authenticators:
                   - lexik_jwt_authentication.jwt_token_authenticator


        main:
            anonymous: lazy
            provider: chain_provider

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api,       roles: ROLE_USER }